# Generated by Django 4.0.4 on 2022-07-25 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.UUIDField(default=uuid.uuid4)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('SkinColor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
