# Generated by Django 4.0.4 on 2022-07-26 22:00

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.UUIDField()),
                ('Season', models.CharField(blank=True, max_length=255, null=True)),
                ('CloathName', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Color', models.CharField(blank=True, max_length=255, null=True)),
                ('Image', models.ImageField(upload_to=Core.models.upload_to)),
            ],
        ),
    ]
