# Generated by Django 3.2.14 on 2022-08-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_firstscreenmodel_secondscreenmodel_thirdscreenmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.UUIDField()),
                ('pathImage', models.CharField(blank=True, max_length=1000, null=True)),
                ('resultid', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
